Pandas

📊 Python Library: In programming, pandas is a powerful data analysis and manipulation library used in Python. It's widely used for handling structured data, like tables or spreadsheets.

In [249]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [250]:
import pandas as pd 
import numpy as np

In [251]:
df =pd.read_csv("laptop_data_cleaned.csv")

In [252]:
df

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1268,Asus,Notebook,4,2.20,10.555257,0,0,100.454670,Intel Core i7,500,0,Nvidia,Windows
1269,Lenovo,2 in 1 Convertible,4,1.80,10.433899,1,1,157.350512,Intel Core i7,0,128,Intel,Windows
1270,Lenovo,2 in 1 Convertible,16,1.30,11.288115,1,1,276.053530,Intel Core i7,0,512,Intel,Windows
1271,Lenovo,Notebook,2,1.50,9.409283,0,0,111.935204,Other Intel Processor,0,0,Intel,Windows
1272,HP,Notebook,6,2.19,10.614129,0,0,100.454670,Intel Core i7,1000,0,AMD,Windows

In [253]:
total_dataset =pd.read_csv("laptopPrice.csv")

In [254]:
total_dataset

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [255]:
total_dataset.head() # top 5 rows

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0

In [256]:
total_dataset.tail() # bottom 5 rows

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [257]:
total_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [258]:
total_dataset.shape

(823, 19)

In [259]:
total_dataset.describe() # summary of data

               Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

In [260]:
total_dataset.columns # list of columns

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'],
      dtype='object')

In [261]:
total_dataset

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [262]:
total_dataset['brand'].value_counts()

brand
ASUS      249
DELL      151
Lenovo    144
HP        136
acer       51
MSI        50
APPLE      28
Avita      14
Name: count, dtype: int64

In [263]:
total_dataset['brand'].unique() # unique values

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [264]:
total_dataset['brand'].nunique() # number of unique values

8

In [265]:
total_dataset['processor_brand'].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [266]:
total_dataset['processor_brand'].nunique()

3

In [267]:
total_dataset.duplicated().sum()

np.int64(21)

In [268]:
total_dataset.drop_duplicates(inplace=True) # remove duplicates

In [269]:
total_dataset.duplicated().sum()

np.int64(0)

In [270]:
total_dataset.isnull().sum() # missing values

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [271]:
total_dataset

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [272]:
df =total_dataset

In [273]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [274]:
apple=df[df['brand']=="APPLE"]

In [275]:
apple.describe()

               Price  Number of Ratings  Number of Reviews
count      23.000000          23.000000          23.000000
mean   157081.304348         853.652174          84.826087
std     54370.286948        1875.694747         174.698611
min     85990.000000           3.000000           1.000000
25%    118990.000000          42.000000           5.000000
50%    149990.000000         108.000000          13.000000
75%    179990.000000         640.000000          70.000000
max    309990.000000        6725.000000         629.000000

In [276]:
apple['ram_gb'].unique()

array(['8 GB', '16 GB', '4 GB', '32 GB'], dtype=object)

In [277]:
apple_8gb =apple[apple['ram_gb']=='8 GB']

In [278]:
apple_8gb['processor_brand'].unique()

array(['Intel', 'M1'], dtype=object)

In [279]:
apple_8gb_intel_brand =apple_8gb[apple_8gb['processor_brand']=='Intel']

In [280]:
apple_8gb_intel_brand

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
309,APPLE,Intel,Core i5,10th,8 GB,LPDDR4X,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,159990,4 stars,32,5
310,APPLE,Intel,Core i5,8th,8 GB,DDR3,512 GB,0 GB,Mac,64-bit,0 GB,Casual,1 year,No,No,172090,4 stars,108,13

In [281]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [282]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [283]:
brand_hp=df[df['brand']=='HP']

In [284]:
brand_hp['processor_brand'].unique()

array(['Intel', 'AMD'], dtype=object)

In [285]:
brand_hp_intel=brand_hp[brand_hp['processor_brand']=='Intel']

In [286]:
brand_hp_intel['ram_gb'].unique()

array(['8 GB', '4 GB', '16 GB'], dtype=object)

In [287]:
bradnd_hp_intel_4gb=brand_hp_intel[brand_hp_intel['ram_gb']=='4 GB']

In [288]:
bradnd_hp_intel_4gb[bradnd_hp_intel_4gb['Price']<=50000]

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
22,HP,Intel,Core i3,7th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32955,4 stars,311,27
23,HP,Intel,Core i5,7th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,46200,4 stars,47,7
57,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44900,4 stars,1029,107
72,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42490,4 stars,5205,561
75,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44376,4 stars,1090,96
114,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,45490,4 stars,523,66
115,HP,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38799,4 stars,30,1
118,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,47990,4 stars,1605,215
124,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,48900,4 stars,1278,135
144,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,3 stars,324,45
145,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,4 stars,69,5
147,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39790,3 stars,40,3
149,HP,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,36490,3 stars,1146,175
154,HP,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,40750,4 stars,1096,116
190,HP,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26470,3 stars,232,23
191,HP,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,27990,3 stars,596,65
438,HP,Intel,Core i5,7th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,44599,4 stars,122,12

In [289]:
df =df.drop(['weight',"warranty","msoffice","rating","Number of Ratings","Number of Reviews"],axis=1)# drop columns and axis =1 means columns

In [290]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No,57490

In [291]:
asus=df[df['brand']=="ASUS"]

In [292]:
asus

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,34649
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,26990
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,22990
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,21990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,ASUS,AMD,Ryzen 9,Not Available,4 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,4 GB,Yes,234990
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No,142990

In [293]:
asus_intl=asus[asus['processor_brand']=='Intel']

In [294]:
asus_intl

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,34649
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,26990
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,22990
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,21990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
630,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,32990
632,ASUS,Intel,Pentium Quad,Not Available,4 GB,LPDDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,27990
633,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,25990
634,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,25990
635,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,30780

In [295]:
asus_4gb=asus_intl[asus_intl['ram_gb']=='4 GB']

In [296]:
asus_4gb

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,34649
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,26990
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,22990
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,21990
14,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,35990
20,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,29890
21,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,23990
24,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,34429
26,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,No,35990
60,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,35990
66,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,39990
68,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,No,41990
70,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,No,39990
74,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,No,48490
81,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,36990
84,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,23490
89,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,No,35990
98,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,No,39990
117,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,No,51649
119,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,No,40990
120,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,No,42990
121,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,No,44890
122,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,No,41490
136,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,35990
139,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,34990
148,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,No,35590
150,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,38990
151,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,No,33990
153,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,24990
156,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,38000
163,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,21490
167,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,23990
169,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,33990
170,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,20490
180,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,No,40990
188,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,18990
189,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,No,17990
623,ASUS,Intel,Pentium Quad,Not Available,4 GB,LPDDR4X,0 GB,512 GB,Windows,64-bit,0 GB,No,45990
624,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,128 GB,0 GB,Windows,32-bit,0 GB,Yes,58100
627,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,33990
630,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,No,32990
632,ASUS,Intel,Pentium Quad,Not Available,4 GB,LPDDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,27990
633,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,25990
634,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,25990
635,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,30780

In [297]:
asus_4gb_touch=asus_4gb[asus_4gb['Touchscreen']=='Yes']

In [298]:
asus_4gb_touch

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
624,ASUS,Intel,Pentium Quad,Not Available,4 GB,DDR4,128 GB,0 GB,Windows,32-bit,0 GB,Yes,58100

In [299]:
total_dataset=total_dataset.drop(['weight','warranty','msoffice','rating','Number of Ratings','Number of Reviews'],axis=1)

In [300]:
total_dataset

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No,57490

In [301]:
cat_cols=total_dataset.select_dtypes(include='object')

In [302]:
cat_cols

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No
...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No

In [303]:
num_cols=total_dataset.select_dtypes(exclude='object')

In [304]:
num_cols

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[802 rows x 1 columns]

In [305]:
cat_cols['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [306]:
brand_dict={'ASUS':0, 'Lenovo':1, 'acer':2, 'Avita':3, 'HP':4, 'DELL':5, 'MSI':6, 'APPLE':7}

In [307]:
brand_dict

{'ASUS': 0,
 'Lenovo': 1,
 'acer': 2,
 'Avita': 3,
 'HP': 4,
 'DELL': 5,
 'MSI': 6,
 'APPLE': 7}

In [308]:
cat_cols['brand']=cat_cols['brand'].map(brand_dict)

In [309]:
cat_cols

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen
0,0,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
1,1,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
2,1,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
3,0,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No
4,0,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No
819,0,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No
820,0,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No
821,0,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No
822,1,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No

In [310]:
cat_cols['brand'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [311]:
cat_cols['processor_brand'].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [312]:
processor_brand_dict={'Intel':0, 'AMD':1, 'M1':2}

In [313]:
cat_cols['processor_brand']=cat_cols['processor_brand'].map(processor_brand_dict)

In [314]:
cat_cols

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen
0,0,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
1,1,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
2,1,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
3,0,0,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No
4,0,0,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No
819,0,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No
820,0,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No
821,0,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No
822,1,1,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No

In [315]:
cat_cols['processor_brand'].unique()

array([0, 1, 2])

In [316]:
cat_cols['processor_name'].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [317]:
processor_name_dict={'Core i3':0, 'Core i5':1, 'Celeron Dual':2, 'Ryzen 5':3, 'Core i7':4,
       'Core i9':5, 'M1':6, 'Pentium Quad':7, 'Ryzen 3':8, 'Ryzen 7':9, 'Ryzen 9':10}

In [318]:
processor_name_dict

{'Core i3': 0,
 'Core i5': 1,
 'Celeron Dual': 2,
 'Ryzen 5': 3,
 'Core i7': 4,
 'Core i9': 5,
 'M1': 6,
 'Pentium Quad': 7,
 'Ryzen 3': 8,
 'Ryzen 7': 9,
 'Ryzen 9': 10}

In [319]:
cat_cols['processor_name']=cat_cols['processor_name'].map(processor_name_dict)

In [320]:
cat_cols

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen
0,0,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
1,1,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
2,1,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No
3,0,0,1,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No
4,0,0,2,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No
819,0,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,No
820,0,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No
821,0,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,No
822,1,1,3,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No

In [321]:
cat_cols['processor_name'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [322]:
cat_cols['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [323]:
df['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [324]:
touch_dict ={
  'No':0, 'Yes':1  
}

In [325]:
df['Touchscreen']=df['Touchscreen'].map(touch_dict)

In [326]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,0,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,0,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,0,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,0,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,0,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,0,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,0,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,0,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,0,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,0,57490

In [327]:
df['processor_brand'].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [328]:
proccessor_brand_dict={
    'Intel':0,
    'AMD':1,
    'M1':2
}

In [329]:
ssd_dict ={
    '0 GB':0,
    '512 GB':512,
    '256 GB':256,
    '128 GB':128,
    '1024 GB':1024,
    '2048 GB':2048,
    '3072 GB':3072
}

In [330]:
cat_cols['ssd']=cat_cols['ssd'].map(ssd_dict)

In [331]:
cat_cols

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen
0,0,0,0,10th,4 GB,DDR4,0,1024 GB,Windows,64-bit,0 GB,No
1,1,0,0,10th,4 GB,DDR4,0,1024 GB,Windows,64-bit,0 GB,No
2,1,0,0,10th,4 GB,DDR4,0,1024 GB,Windows,64-bit,0 GB,No
3,0,0,1,10th,8 GB,DDR4,512,0 GB,Windows,32-bit,2 GB,No
4,0,0,2,Not Available,4 GB,DDR4,0,512 GB,Windows,64-bit,0 GB,No
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,Not Available,4 GB,DDR4,1024,0 GB,Windows,64-bit,0 GB,No
819,0,1,10,Not Available,4 GB,DDR4,1024,0 GB,Windows,64-bit,0 GB,No
820,0,1,10,Not Available,4 GB,DDR4,1024,0 GB,Windows,64-bit,4 GB,No
821,0,1,10,Not Available,4 GB,DDR4,1024,0 GB,Windows,64-bit,4 GB,No
822,1,1,3,10th,8 GB,DDR4,512,0 GB,DOS,64-bit,0 GB,No

In [332]:
ram_type_dict ={
    'DDR4':0,
    'LPDDR4':1,
    'LPDDR4X':2,
    'DDR5':3,
    'DDR3':4,
    'LPDDR3':5
}

In [333]:
cat_cols['ram_type']=cat_cols['ram_type'].map(ram_type_dict)

In [334]:
cat_cols

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen
0,0,0,0,10th,4 GB,0,0,1024 GB,Windows,64-bit,0 GB,No
1,1,0,0,10th,4 GB,0,0,1024 GB,Windows,64-bit,0 GB,No
2,1,0,0,10th,4 GB,0,0,1024 GB,Windows,64-bit,0 GB,No
3,0,0,1,10th,8 GB,0,512,0 GB,Windows,32-bit,2 GB,No
4,0,0,2,Not Available,4 GB,0,0,512 GB,Windows,64-bit,0 GB,No
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,Not Available,4 GB,0,1024,0 GB,Windows,64-bit,0 GB,No
819,0,1,10,Not Available,4 GB,0,1024,0 GB,Windows,64-bit,0 GB,No
820,0,1,10,Not Available,4 GB,0,1024,0 GB,Windows,64-bit,4 GB,No
821,0,1,10,Not Available,4 GB,0,1024,0 GB,Windows,64-bit,4 GB,No
822,1,1,3,10th,8 GB,0,512,0 GB,DOS,64-bit,0 GB,No

In [335]:
cat_cols['processor_gnrtn'].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [336]:
processor_gnrtn_dict={'10th':0, 'Not Available':1, '11th':2, '7th':3, '8th':4, '9th':5, '4th':6,
       '12th':7}

In [337]:
cat_cols['processor_gnrtn']=cat_cols['processor_gnrtn'].map(processor_gnrtn_dict)

In [338]:
cat_cols['ram_gb'].unique()

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [339]:
ram_gb_dict={'4 GB':0, '8 GB':1, '16 GB':2, '32 GB':3}

In [340]:
cat_cols['ram_gb']=cat_cols['ram_gb'].map(ram_gb_dict)

In [341]:
cat_cols['hdd'].unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [342]:
hdd_dict={'1024 GB':0, '0 GB':1, '512 GB':2, '2048 GB':3}

In [343]:
cat_cols['hdd']=cat_cols['hdd'].map(hdd_dict)

In [344]:
cat_cols['os'].unique()

array(['Windows', 'DOS', 'Mac'], dtype=object)

In [345]:
os_dict={'Windows':0, 'DOS':1, 'Mac':2}

In [346]:
cat_cols['os']=cat_cols['os'].map(os_dict)

In [347]:
cat_cols['os_bit'].unique()

array(['64-bit', '32-bit'], dtype=object)

In [348]:
os_bit_dict={'64-bit':0, '32-bit':1}

In [349]:
cat_cols['os_bit']=cat_cols['os_bit'].map(os_bit_dict)

In [350]:
cat_cols['graphic_card_gb'].unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [351]:
cat_cols['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [352]:

Touchscreen_dict={'No':0, 'Yes':1}
cat_cols['Touchscreen']=cat_cols['Touchscreen'].map(Touchscreen_dict)

In [353]:
graphic_card_gb_dict={'0 GB':0, '2 GB':1, '4 GB':2, '6 GB':3, '8 GB':4}

In [354]:
cat_cols['graphic_card_gb']=cat_cols['graphic_card_gb'].map(graphic_card_gb_dict)

In [355]:
df['processor_brand']=df['processor_brand'].map(proccessor_brand_dict)

In [356]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
0,ASUS,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,0,34649
1,Lenovo,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,0,38999
2,Lenovo,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,0,39999
3,ASUS,0,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,0,69990
4,ASUS,0,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,0,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,0,135990
819,ASUS,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,0,144990
820,ASUS,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,0,149990
821,ASUS,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,0,142990
822,Lenovo,1,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,0,57490

In [357]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            802 non-null    object
 1   processor_brand  802 non-null    int64
 2   processor_name   802 non-null    object
 3   processor_gnrtn  802 non-null    object
 4   ram_gb           802 non-null    object
 5   ram_type         802 non-null    object
 6   ssd              802 non-null    object
 7   hdd              802 non-null    object
 8   os               802 non-null    object
 9   os_bit           802 non-null    object
 10  graphic_card_gb  802 non-null    object
 11  Touchscreen      802 non-null    int64
 12  Price            802 non-null    int64
dtypes: int64(3), object(10)
memory usage: 87.7+ KB

In [358]:
complete_df =pd.concat([cat_cols,num_cols],axis=1)

In [359]:
complete_df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen,Price
0,0,0,0,0,0,0,0,0,0,0,0,0,34649
1,1,0,0,0,0,0,0,0,0,0,0,0,38999
2,1,0,0,0,0,0,0,0,0,0,0,0,39999
3,0,0,1,0,1,0,512,1,0,1,1,0,69990
4,0,0,2,1,0,0,0,2,0,0,0,0,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,1,0,0,1024,1,0,0,0,0,135990
819,0,1,10,1,0,0,1024,1,0,0,0,0,144990
820,0,1,10,1,0,0,1024,1,0,0,2,0,149990
821,0,1,10,1,0,0,1024,1,0,0,2,0,142990
822,1,1,3,0,1,0,512,1,1,0,0,0,57490

In [360]:
x=complete_df.drop('Price',axis=1)  #cols=1---axis=1
y=complete_df[['Price']]

In [361]:
x

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen
0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,1,0,512,1,0,1,1,0
4,0,0,2,1,0,0,0,2,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,1,0,0,1024,1,0,0,0,0
819,0,1,10,1,0,0,1024,1,0,0,0,0
820,0,1,10,1,0,0,1024,1,0,0,2,0
821,0,1,10,1,0,0,1024,1,0,0,2,0
822,1,1,3,0,1,0,512,1,1,0,0,0

In [362]:
y

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[802 rows x 1 columns]

In [363]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=0)

In [364]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((641, 12), (161, 12), (641, 1), (161, 1))

In [365]:
from sklearn.linear_model import LinearRegression

In [366]:
lr=LinearRegression()

In [367]:
lr.fit(x_train,y_train)

LinearRegression()

In [368]:
x_train

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,Touchscreen
371,5,0,1,2,1,0,512,1,0,0,1,0
444,2,0,1,2,1,0,256,0,0,0,0,0
78,1,0,0,0,0,0,256,1,0,1,0,0
66,0,0,0,2,0,0,256,1,0,0,0,0
743,0,1,9,1,1,0,512,1,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
784,1,1,9,1,0,0,1024,1,0,0,3,0
196,2,0,1,1,1,3,0,2,0,1,2,0
650,5,1,8,1,0,0,512,1,0,0,0,0
575,2,0,4,0,2,0,2048,1,0,0,4,0
705,0,1,3,1,0,2,512,1,0,0,0,1

In [369]:
lr.score(x_test,y_test)

0.5676187466661224

In [370]:
lr.score(x_train,y_train)

0.7135658561160404

In [371]:
from sklearn.svm import SVR

In [372]:
Ssvr_obj=SVR()

In [373]:
Ssvr_obj.fit(x_train,y_train)

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [374]:
Ssvr_obj.score(x_train,y_train)

-0.07831127084932099

In [375]:
Ssvr_obj.score(x_test,y_test)

-0.0712256068564785

In [376]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [377]:
knr=KNeighborsRegressor()

In [378]:
knr.fit(x_train,y_train)

KNeighborsRegressor()

In [379]:
print("testing score:- ",knr.score(x_test,y_test))

testing score:-  0.6320090781644154

In [380]:
print("training score:- ",knr.score(x_train,y_train))

training score:-  0.7635149982654311

In [381]:
knr.predict(x_test)

array([[ 34991.8],
       [ 80791.8],
       [ 46518. ],
       [ 46131.8],
       [ 50870. ],
       [ 61572. ],
       [ 64091.8],
       [128190. ],
       [ 80790. ],
       [139990. ],
       [ 40877.8],
       [ 46518. ],
       [ 80590. ],
       [ 46070. ],
       [ 46651.8],
       [ 49370. ],
       [ 61291.8],
       [ 21490. ],
       [ 52565.4],
       [ 66786.6],
       [ 58390. ],
       [ 58390. ],
       [ 61391.8],
       [ 70251.8],
       [ 50090. ],
       [ 86093.8],
       [ 76850. ],
       [ 81830. ],
       [ 80819.6],
       [ 40483.8],
       [ 83507.8],
       [ 43254.6],
       [ 60863.8],
       [ 55190. ],
       [113067. ],
       [ 35303.8],
       [ 41170. ],
       [ 80190. ],
       [ 61573.6],
       [ 63091.6],
       [124692. ],
       [ 63302.2],
       [ 51991.8],
       [ 43190. ],
       [182290. ],
       [ 57712. ],
       [ 43731.8],
       [ 54972. ],
       [137590. ],
       [ 63589.6],
       [137590. ],
       [ 34232. ],
       [ 88291.4],
       [136277.8],
       [ 57712. ],
       [143913.6],
       [ 79512. ],
       [ 80290. ],
       [218493.6],
       [ 86015.6],
       [ 35523.8],
       [ 67171.8],
       [ 78710. ],
       [ 65092. ],
       [ 51570. ],
       [ 74370. ],
       [113790. ],
       [ 64992. ],
       [ 73488. ],
       [ 73483.8],
       [ 44479.2],
       [ 57030. ],
       [ 70207. ],
       [ 55190. ],
       [ 36123.8],
       [ 55190. ],
       [ 82573.8],
       [ 91790. ],
       [ 61773.8],
       [ 83052. ],
       [ 73488. ],
       [ 71833.8],
       [131963.4],
       [ 58772. ],
       [ 67171.8],
       [104504.2],
       [ 45550. ],
       [ 46651.8],
       [ 60863.8],
       [ 55190. ],
       [ 74713.8],
       [ 70491.6],
       [ 71176. ],
       [ 58855.6],
       [ 40483.8],
       [ 41145. ],
       [ 67171.8],
       [ 89790. ],
       [ 71610. ],
       [ 33148. ],
       [ 64313. ],
       [ 51277.4],
       [ 50913.8],
       [ 39783. ],
       [104504.2],
       [ 55190. ],
       [ 43933.8],
       [176783. ],
       [ 88990. ],
       [ 39811.8],
       [ 82573.8],
       [ 56534. ],
       [ 71610. ],
       [ 41170. ],
       [ 84790. ],
       [118190. ],
       [ 86015.6],
       [ 76825.4],
       [ 80819.6],
       [ 41610. ],
       [ 81830. ],
       [134164.6],
       [ 73488. ],
       [140390. ],
       [ 63902.2],
       [ 67708. ],
       [ 38184. ],
       [ 80819.6],
       [ 81190. ],
       [ 40483.8],
       [ 98194. ],
       [ 43731.8],
       [ 60409.8],
       [ 37230. ],
       [ 36123.8],
       [147390. ],
       [ 58390. ],
       [ 74572. ],
       [104594.6],
       [ 64111.8],
       [ 80819.6],
       [ 66913. ],
       [ 70207. ],
       [ 80590. ],
       [ 80790. ],
       [ 62990. ],
       [ 61264. ],
       [ 41301.8],
       [ 59391.8],
       [ 40629.6],
       [ 43190. ],
       [ 60572. ],
       [ 35770. ],
       [ 51277.4],
       [ 43190. ],
       [ 46070. ],
       [ 43492. ],
       [ 48152. ],
       [ 58089.8],
       [ 66809.2],
       [ 48152. ]])

In [382]:
from sklearn.tree  import DecisionTreeRegressor,DecisionTreeClassifier

In [383]:
dtr=DecisionTreeRegressor()

In [384]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [385]:
print("testing score:- ",dtr.score(x_test,y_test))

testing score:-  0.5326229388869212

In [386]:
print("training score:- ",dtr.score(x_train,y_train))

training score:-  0.9642112584226342

In [387]:
dtr.predict(x_test)

array([ 48790.        ,  64990.        ,  46518.        ,  58799.        ,
        53990.        ,  61990.        ,  64990.        ,  62990.        ,
       162399.        , 192990.        ,  36803.        ,  46518.        ,
        80656.66666667,  43240.        ,  44326.33333333,  43433.        ,
        52212.25      ,  21490.        ,  94190.        ,  50990.        ,
        62491.21428571,  62491.21428571,  63990.        ,  70140.        ,
        61990.        ,  69899.        ,  74990.        ,  90190.        ,
        90064.        ,  38690.        ,  76190.        ,  43433.        ,
        59900.        ,  57740.        , 116990.        ,  32890.        ,
        42465.        ,  88990.        ,  69899.        ,  66745.        ,
       124692.        ,  56515.5       ,  54990.        ,  53990.        ,
       218590.        ,  59990.        ,  66990.        ,  34990.        ,
       158323.33333333,  63249.5       , 158323.33333333,  34095.        ,
        84990.        ,  80656.66666667,  59990.        , 129990.        ,
       103526.66666667,  89990.        , 265998.        , 102990.        ,
        33990.        ,  64490.        ,  75990.        ,  81990.        ,
        62990.        ,  69490.        , 122990.        ,  94000.        ,
        73488.        ,  64990.        ,  44427.        ,  59990.        ,
        65556.        ,  57740.        ,  36990.        ,  57740.        ,
        57990.        ,  98740.        ,  56993.        , 106490.        ,
        73488.        ,  59990.        , 131500.        ,  61293.33333333,
        64490.        ,  82490.        ,  41790.        ,  44326.33333333,
        59900.        ,  57740.        ,  74259.83333333,  63490.        ,
        64240.        ,  59975.6       ,  52632.        ,  32955.        ,
        64490.        ,  74990.        , 113790.        ,  28385.        ,
        71990.        ,  45490.        ,  41490.        ,  39890.        ,
        82490.        ,  57740.        ,  31999.        , 213323.33333333,
       211753.        ,  41999.        ,  57990.        ,  49800.        ,
       113790.        ,  42465.        ,  74990.        ,  72990.        ,
       102990.        , 218590.        ,  79990.        ,  40656.66666667,
        90190.        , 211753.        ,  73488.        , 166990.        ,
        66490.        ,  86867.        ,  35990.        ,  79990.        ,
        63990.        ,  52632.        ,  87996.66666667, 119990.        ,
        73999.        ,  20990.        ,  36990.        , 151990.        ,
        62491.21428571,  70140.        , 125394.        ,  76990.        ,
        63990.        ,  68893.75      ,  65556.        ,  80656.66666667,
        79990.        ,  60490.        ,  49890.        ,  51990.        ,
        56994.5       ,  40990.        ,  38990.        ,  55740.        ,
        38990.        ,  45490.        ,  38990.        ,  43240.        ,
        43492.        ,  49800.        ,  66745.        ,  84086.        ,
        49800.        ])

In [388]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [389]:
rfr=RandomForestRegressor()

In [390]:
rfr.fit(x_train,y_train)

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [391]:
print("testing score:- ",rfr.score(x_test,y_test))

testing score:-  0.7223844292719128

In [392]:
print("training score:- ",rfr.score(x_train,y_train))

training score:-  0.9282234996145249

In [393]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
print(gnb.score(x_test,y_test))
print(gnb.score(x_train,y_train))

0.0
0.41965678627145087

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [394]:
from sklearn.datasets import load_iris
data=load_iris()
x=data.data
y=data.target

In [395]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [396]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [397]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
print("testing score:-",gnb.score(x_test,y_test))
print("training score:",gnb.score(x_train,y_train))

testing score:- 0.9666666666666667
training score: 0.95

In [398]:
from sklearn.ensemble import RandomForestRegressor

rf =RandomForestRegressor()

rf.fit(x_train,y_train)

print("testing score :-",rf.score(x_test,y_test))

print("training score :-",rf.score(x_train,y_train))

testing score :- 0.9915484896661367
training score :- 0.9906293912860006

In [399]:
import joblib
joblib.dump(rf,"laptop_price.joblib")

['laptop_price.joblib']

In [400]:
model=joblib.load("laptop_price.joblib")

In [401]:
pred=model.predict(x_test)

In [402]:
pred

array([0.  , 0.  , 1.04, 1.  , 1.98, 1.99, 0.  , 0.  , 1.  , 1.  , 2.  ,
       1.93, 1.  , 1.9 , 0.  , 1.  , 0.  , 1.  , 1.99, 0.  , 0.  , 1.  ,
       2.  , 0.  , 1.  , 0.  , 0.  , 1.99, 2.  , 1.6 ])

In [403]:
prediction_history={"prediction_price":pred,"actual_price":y_test}

In [404]:
pd.DataFrame(prediction_history)

    prediction_price  actual_price
0               0.00             0
1               0.00             0
2               1.04             1
3               1.00             1
4               1.98             2
5               1.99             2
6               0.00             0
7               0.00             0
8               1.00             1
9               1.00             1
10              2.00             2
11              1.93             2
12              1.00             1
13              1.90             2
14              0.00             0
15              1.00             1
16              0.00             0
17              1.00             1
18              1.99             2
19              0.00             0
20              0.00             0
21              1.00             1
22              2.00             2
23              0.00             0
24              1.00             1
25              0.00             0
26              0.00             0
27              1.99             2
28              2.00             2
29              1.60             2